name: iperf-client
accessor:
  username: admin@opencord.org
  password: letmein
  endpoint: xos-core:50051
models_dir: "/opt/xos/synchronizers/iperf_client/models"
steps_dir: "/opt/xos/synchronizers/iperf_client/steps"
model_policies_dir: "/opt/xos/synchronizers/iperf_client/model_policies"
required_models:
  - IperfClientService
  - IperfClientServiceInstance
  - KubernetesService
  - KubernetesServiceInstance
  - KubernetesConfigMap
  - KubernetesSecret
  - KubernetesConfigVolumeMount
  - KubernetesSecretVolumeMount
logging:
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
  loggers:
    'multistructlog':
      handlers:
          - console
      level: DEBUG
