FROM xosproject/xos-synchronizer-base:2.0.0

COPY xos/synchronizer /opt/xos/synchronizers/simple_subscriber
COPY VERSION /opt/xos/synchronizers/simple_subscriber/

ENTRYPOINT []

WORKDIR "/opt/xos/synchronizers/simple_subscriber"

CMD bash -c "python simple-subscriber-synchronizer.py"
